language: cpp

sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - bison
            - flex
            - texinfo
            - cfitsio-dev
            - autoconf-archive
            - lcov
            - python-pip

      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
            - clang++-3.9
            - libc++-dev
            - bison
            - flex
            - texinfo
            - cfitsio-dev
            - autoconf-archive

      env:  # For whatever reason CXXFLAGS is not honored.  Use CXX.
        - MATRIX_EVAL="CC=clang-3.9 && CXX='clang++-3.9 -stdlib=libc++'"

    - os: osx
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++-5" ]]; then
        wget https://github.com/gabime/spdlog/archive/v0.17.0.tar.gz -O /tmp/spdlog.tar.gz;
        tar xf /tmp/spdlog.tar.gz spdlog-0.17.0/include/;
        export CPPFLAGS="$CPPFLAGS -I$PWD/spdlog-0.17.0/include";
      fi
    - ./bootstrap

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++-5" ]]; then
          ./configure --disable-silent-rules --enable-code-coverage;
          make check-code-coverage;
      else
          ./configure --disable-silent-rules && make check;
      fi

before_install:
    - eval "${MATRIX_EVAL}"
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++-5" ]]; then
        pip install --user cpp-coveralls;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          brew install cfitsio bison flex texinfo autoconf-archive spdlog;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          for p in bison gettext flex texinfo; do
              export PATH="/usr/local/opt/$p/bin:$PATH";
          done;
      fi

after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++-5" ]]; then
          cpp-coveralls --exclude tests --gcov-options '\-lp';
      fi
