language: cpp

sudo: false

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - cfitsio-dev
      - bison
      - flex
      - texinfo

before_script:
  - ./bootstrap
  - ./configure --disable-silent-rules && make && make check

before_install:
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then brew tap homebrew/science; fi
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then brew install cfitsio bison flex texinfo; fi
