language: cpp
dist: xenial
sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++
            - texinfo
            - libcfitsio-dev
            - autoconf-archive
            - lcov
            - python-pip

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
            - clang++-7
            - texinfo
            - libcfitsio-dev
            - autoconf-archive

    - os: osx
      compiler: clang
      addons:
        homebrew:
          packages:
          - bison
          - flex
          - texinfo
          - autoconf-archive
          - fmt

before_script:
    - ./bootstrap

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++" ]]; then
          ./configure --disable-silent-rules --enable-code-coverage;
          make check-code-coverage;
      else
          ./configure --disable-silent-rules && make check;
      fi

before_install:
    - eval "${MATRIX_EVAL}"
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++" ]]; then
        pip install --user cpp-coveralls;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          for p in bison gettext flex texinfo; do
              export PATH="/usr/local/opt/$p/bin:$PATH";
          done;
      fi

after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++" ]]; then
          cpp-coveralls --exclude src/parse.hh --exclude src/parse.cc --exclude src/lexer.cc --exclude opt --exclude tests --gcov-options '\-lp';
      fi
