name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt install g++ libcfitsio-dev autoconf-archive lcov
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure --enable-code-coverage
    - name: make
      run: make
    - name: make check
      run: make check-code-coverage \
             CODE_COVERAGE_OUTPUT_FILE=lcov.info \
             CODE_COVERAGE_LCOV_OPTIONS="--no-external --exclude .. --exclude */src/parse.hh --exclude */src/parse.cc --exclude */src/lexer.cc --exclude */opt/* --exclude */tests/*"
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./lcov.info
