name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
      	   brew update
      	   brew install bison flex texinfo autoconf-archive fmt
	   for p in bison gettext flex texinfo; do
              export PATH="/usr/local/opt/$p/bin:$PATH";
           done;
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make install
      run: make install
    - name: make installcheck
      run: LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH make installcheck
    - name: make uninstall
      run: make uninstall
